// import { CreateRoleDto } from './dto/create-role.dto'

export const baseRoles = [
  {
      "name": "Наблюдатель",
      "key": "",
      "description": "Наблюдатель",
      "permissions": [
          "profile_updateself",
          "user_read_basic"
      ],
      "workspace_id": ""
  },
  {
      "name": "Автор задач",
      "key": "",
      "description": "Автор задач может создавать новые задачи и комментарии, просматривать существующие задачи и комментарии, а также управлять своим профилем.",
      "permissions": [
          "project_read_basic",
          "profile_updateself",
          "link_issue",
          "create_attachment_issue",
          "create_comment",
          "read_comment",
          "update_comment",
          "delete_comment",
          "read_report",
          "read_issue",
          "create_issue"
      ],
      "workspace_id": ""
  },
  {
      "name": "Администратор проекта",
      "key": "project-admin",
      "description": "Администратор проекта имеет те же права доступа, что разработчик, и может управлять параметрами проекта, такими как исполнители, поля и рабочие процессы.",
      "permissions": [
          "organization_read",
          "project_create",
          "project_read_basic",
          "project_read",
          "project_update",
          "role_read",
          "profile_updateself",
          "user_create",
          "user_read_basic",
          "user_read",
          "group_create",
          "group_read",
          "group_update",
          "group_delete",
          "update_issue",
          "delete_issue",
          "link_issue",
          "apply_commands_silently",
          "update_watchers",
          "create_attachment_issue",
          "update_attachment_issue",
          "delete_attachment_issue",
          "create_comment",
          "read_comment",
          "update_comment",
          "delete_comment",
          "create_watch_folder",
          "update_watch_folder",
          "delete_watch_folder",
          "share_watch_folder",
          "read_work_item",
          "update_work_item",
          "create_work_item",
          "read_report",
          "read_issue",
          "private_read_issue",
          "create_issue",
          "view_watchers",
          "view_voters",
          "update_not_own_comment",
          "delete_not_own_comment",
          "update_not_own_work_item",
          "create_not_own_work_item",
          "create_report",
          "share_report",
          "read_article",
          "private_update_issue",
          "create_article",
          "update_article",
          "delete_article",
          "read_article_comment",
          "create_article_comment",
          "update_article_comment",
          "delete_article_comment"
      ],
      "workspace_id": ""
  },
  {
      "name": "Контрибьютор",
      "key": "contributor",
      "description": "Роль контрибьютора предназначается для пользователей, которые создают задачи и работают с ними. Контрибьюторы могут создавать новые задачи, добавлять комментарии, просматривать существующие задачи и комментарии, обновлять большинство атрибутов задач и управлять своими профилями.",
      "permissions": [
          "organization_read",
          "project_read_basic",
          "profile_updateself",
          "user_read_basic",
          "user_read",
          "update_issue",
          "delete_issue",
          "link_issue",
          "update_watchers",
          "create_attachment_issue",
          "update_attachment_issue",
          "delete_attachment_issue",
          "create_comment",
          "read_comment",
          "update_comment",
          "delete_comment",
          "create_watch_folder",
          "update_watch_folder",
          "delete_watch_folder",
          "share_watch_folder",
          "read_work_item",
          "update_work_item",
          "create_work_item",
          "read_report",
          "read_issue",
          "private_read_issue",
          "create_issue",
          "view_watchers",
          "view_voters",
          "create_report",
          "share_report",
          "read_article",
          "private_update_issue",
          "create_article",
          "read_article_comment",
          "create_article_comment"
      ],
      "workspace_id": ""
  },
  {
      "name": "Системный администратор",
      "key": "",
      "description": "Администратор имеет права на выполнение любых операций.",
      "permissions": [
          "organization_read",
          "organization_create",
          "organization_update",
          "organization_delete",
          "project_create",
          "project_read_basic",
          "project_read",
          "project_update",
          "project_delete",
          "role_read",
          "role_manage",
          "profile_updateself",
          "user_create",
          "user_read_basic",
          "user_read",
          "user_update",
          "user_delete",
          "group_create",
          "group_read",
          "group_update",
          "group_delete",
          "low_level_read",
          "low_level",
          "update_issue",
          "delete_issue",
          "link_issue",
          "apply_commands_silently",
          "update_watchers",
          "create_attachment_issue",
          "update_attachment_issue",
          "delete_attachment_issue",
          "create_comment",
          "read_comment",
          "update_comment",
          "delete_comment",
          "create_watch_folder",
          "update_watch_folder",
          "delete_watch_folder",
          "share_watch_folder",
          "read_work_item",
          "update_work_item",
          "create_work_item",
          "read_report",
          "read_issue",
          "private_read_issue",
          "create_issue",
          "view_watchers",
          "view_voters",
          "update_not_own_comment",
          "delete_not_own_comment",
          "update_not_own_work_item",
          "create_not_own_work_item",
          "create_report",
          "share_report",
          "read_article",
          "private_update_issue",
          "read_hidden_stuff",
          "create_article",
          "update_article",
          "delete_article",
          "read_article_comment",
          "create_article_comment",
          "update_article_comment",
          "delete_article_comment"
      ],
      "workspace_id": ""
  },
  {
      "name": "Читатель задач",
      "key": "",
      "description": "Читатель задач может только просматривать задачи и комментарии.",
      "permissions": [
          "project_read_basic",
          "read_comment",
          "read_report",
          "read_issue"
      ],
      "workspace_id": ""
  }
]