// import { CreateRoleDto } from './dto/create-role.dto'

export const baseRoles = [
  {
      "name": "RN_OBSERVER",
      "key": "",
      "description": "RD_OBSERVER",
      "permissions": [
          "profile_updateself",
          "user_read_basic"
      ],
      "workspace_id": ""
  },
  {
      "name": "RN_REPORTER",
      "key": "",
      "description": "RD_REPORTER",
      "permissions": [
          "project_read_basic",
          "profile_updateself",
          "link_issue",
          "create_attachment_issue",
          "create_comment",
          "read_comment",
          "update_comment",
          "delete_comment",
          "read_report",
          "read_issue",
          "create_issue"
      ],
      "workspace_id": ""
  },
  {
      "name": "RN_ADMIN",
      "key": "project-admin",
      "description": "RD_ADMIN",
      "permissions": [
          "organization_read",
          "project_create",
          "project_read_basic",
          "project_read",
          "project_update",
          "role_read",
          "profile_updateself",
          "user_create",
          "user_read_basic",
          "user_read",
          "group_create",
          "group_read",
          "group_update",
          "group_delete",
          "update_issue",
          "delete_issue",
          "link_issue",
          "apply_commands_silently",
          "update_watchers",
          "create_attachment_issue",
          "update_attachment_issue",
          "delete_attachment_issue",
          "create_comment",
          "read_comment",
          "update_comment",
          "delete_comment",
          "create_watch_folder",
          "update_watch_folder",
          "delete_watch_folder",
          "share_watch_folder",
          "read_work_item",
          "update_work_item",
          "create_work_item",
          "read_report",
          "read_issue",
          "private_read_issue",
          "create_issue",
          "view_watchers",
          "view_voters",
          "update_not_own_comment",
          "delete_not_own_comment",
          "update_not_own_work_item",
          "create_not_own_work_item",
          "create_report",
          "share_report",
          "read_article",
          "private_update_issue",
          "create_article",
          "update_article",
          "delete_article",
          "read_article_comment",
          "create_article_comment",
          "update_article_comment",
          "delete_article_comment"
      ],
      "workspace_id": ""
  },
  {
      "name": "RN_CONTRIBUTOR",
      "key": "contributor",
      "description": "RD_CONTRIBUTOR",
      "permissions": [
          "organization_read",
          "project_read_basic",
          "profile_updateself",
          "user_read_basic",
          "user_read",
          "update_issue",
          "delete_issue",
          "link_issue",
          "update_watchers",
          "create_attachment_issue",
          "update_attachment_issue",
          "delete_attachment_issue",
          "create_comment",
          "read_comment",
          "update_comment",
          "delete_comment",
          "create_watch_folder",
          "update_watch_folder",
          "delete_watch_folder",
          "share_watch_folder",
          "read_work_item",
          "update_work_item",
          "create_work_item",
          "read_report",
          "read_issue",
          "private_read_issue",
          "create_issue",
          "view_watchers",
          "view_voters",
          "create_report",
          "share_report",
          "read_article",
          "private_update_issue",
          "create_article",
          "read_article_comment",
          "create_article_comment"
      ],
      "workspace_id": ""
  },
  {
      "name": "RN_SYSTEM_ADMIN",
      "key": "",
      "description": "RD_SYSTEM_ADMIN",
      "permissions": [
          "organization_read",
          "organization_create",
          "organization_update",
          "organization_delete",
          "project_create",
          "project_read_basic",
          "project_read",
          "project_update",
          "project_delete",
          "role_read",
          "role_manage",
          "profile_updateself",
          "user_create",
          "user_read_basic",
          "user_read",
          "user_update",
          "user_delete",
          "group_create",
          "group_read",
          "group_update",
          "group_delete",
          "low_level_read",
          "low_level",
          "update_issue",
          "delete_issue",
          "link_issue",
          "apply_commands_silently",
          "update_watchers",
          "create_attachment_issue",
          "update_attachment_issue",
          "delete_attachment_issue",
          "create_comment",
          "read_comment",
          "update_comment",
          "delete_comment",
          "create_watch_folder",
          "update_watch_folder",
          "delete_watch_folder",
          "share_watch_folder",
          "read_work_item",
          "update_work_item",
          "create_work_item",
          "read_report",
          "read_issue",
          "private_read_issue",
          "create_issue",
          "view_watchers",
          "view_voters",
          "update_not_own_comment",
          "delete_not_own_comment",
          "update_not_own_work_item",
          "create_not_own_work_item",
          "create_report",
          "share_report",
          "read_article",
          "private_update_issue",
          "read_hidden_stuff",
          "create_article",
          "update_article",
          "delete_article",
          "read_article_comment",
          "create_article_comment",
          "update_article_comment",
          "delete_article_comment"
      ],
      "workspace_id": ""
  },
  {
      "name": "RN_ISSUE_READER",
      "key": "",
      "description": "RD_ISSUE_READER",
      "permissions": [
          "project_read_basic",
          "read_comment",
          "read_report",
          "read_issue"
      ],
      "workspace_id": ""
  }
]